### ISSUE TITLE
`spito check` doesn't work

### ISSUE THREAD

**Issue by cooligus** [avorty/spito#104]
This spito.yml
```yml
repo_url: https://github.com/avorty/spito-ruleset
git_prefix: github.com
identifier: avorty/spito-ruleset

rules:
    dbus: ./rules/dbus.lua
    nerd-fonts: ./rules/nerd-fonts.lua
    info: ./rules/info.lua
```

Causes this error when executing `spito g samba`
```
[error] yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `./rules...` into cmd.Rule
  line 7: cannot unmarshal !!str `./rules...` into cmd.Rule
  line 8: cannot unmarshal !!str `./rules...` into cmd.Rule
```

As a result command `spito check avorty/spito-ruleset info` throws this output:
```
Failed to read script called: info from github.com/avorty/spito-ruleset
open /home/jarek/.local/state/spito/rulesets/github.com/avorty/spito-ruleset/spito.yaml: no such file or directory
```
BTW it doesn't end with a new line:
![image](https://github.com/avorty/spito/assets/67282004/74b7c8d0-ecc6-4b09-a74f-b3118148ed28)
